title: Ty Tinker # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Security Analytics Graduate Student at the University of Colorado, Boulder
  <br><br>
  A place to share my analytics work through a graduate program and personal endeavors
  <br><br>
  <a href="https://www.linkedin.com/in/tytinker/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
